export const USER_SIGNIN_REQUEST="USER_SIGNIN_REQUEST"
export const USER_SIGNIN_SUCCESS="USER_SIGNIN_SUCCESS"
export const USER_SIGNIN_FAIL="USER_SIGNIN_FAIL"
export const USER_SIGN_OUT="USER_SIGN_OUT"

export const PROFIL_SAVE_REQUEST="PROFIL_SAVE_REQUEST"
export const PROFIL_SAVE_SUCCESS="PRODIL_SAVE_SUCCESS"
export const PROFIL_SAVE_FAIL="PROFIL_SAVE_FAIL"

export const USERS_LIST_REQUEST="USERS_LIST_REQUEST"
export const USERS_LIST_SUCCESS="USERS_LIST_SUCCESS"
export const USERS_LIST_FAIL="USERS_LIST_FAIL"
