export const AGENT_INFOS_REQUEST = 'AGENT_INFOS_REQUEST'
export const AGENT_INFOS_SUCCESS = 'AGENT_INFOS_SUCCESS'
export const AGENT_INFOS_FAIL = 'AGENT_INFOS_FAIL'

export const AGENT_CREATE_REQUEST = 'AGENT_CREATE_REQUEST'
export const AGENT_CREATE_SUCCESS = 'AGENT_CREATE_SUCCESS'
export const AGENT_CREATE_FAIL = 'AGENT_CREATE_FAIL'