export const AGENT_INFOS_REQUEST = 'AGENT_INFOS_REQUEST'
export const AGENT_INFOS_SUCCESS = 'AGENT_INFOS_SUCCESS'
export const AGENT_INFOS_FAIL = 'AGENT_INFOS_FAIL'

export const AGENT_CREATE_REQUEST = 'AGENT_CREATE_REQUEST'
export const AGENT_CREATE_SUCCESS = 'AGENT_CREATE_SUCCESS'
export const AGENT_CREATE_FAIL = 'AGENT_CREATE_FAIL'

export const AGENT_SINGLE_DETAILS_REQUEST = 'AGENT_SINGLE_DETAILS_REQUEST'
export const AGENT_SINGLE_DETAILS_SUCCESS = 'AGENT_SINGLE_DETAILS_SUCCESS'
export const AGENT_SINGLE_DETAILS_FAIL = 'AGENT_SINGLE_DETAILS_FAIL'

export const AGENT_DELETE_SUCCESS = 'AGENT_DELETE_SUCCESS'
export const AGENT_DELETE_FAIL = 'AGENT_DELETE_FAIL'

export const AGENT_UPDATE_SUCCESS = 'AGENT_UPDATE_SUCCESS'
export const AGENT_UPDATE_FAIL = 'AGENT_UPDATE_FAIL'