export const PROJECT_INFOS_REQUEST = 'PROJECT_INFOS_REQUEST'
export const PROJECT_INFOS_SUCCESS = 'PROJECT_INFOS_SUCCESS'
export const PROJECT_INFOS_FAIL = 'PROJECT_INFOS_FAIL'

export const PROJECT_CREATE_REQUEST = 'PROJECT_CREATE_REQUEST'
export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS'
export const PROJECT_CREATE_FAIL = 'PROJECT_CREATE_FAIL'